#!/usr/bin/env python3
"""Add Obsidian frontmatter to markdown files.

Policy (safe by default):
- Only add frontmatter if file has none.
- Do NOT rewrite existing frontmatter.
- Tags generated by light rules (path + keyword).

Usage:
  python add-frontmatter.py <root_dir> [--dry-run]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from datetime import date

def has_frontmatter(text: str) -> bool:
    lines = text.splitlines()
    return len(lines) >= 2 and lines[0].strip() == '---' and '---' in [l.strip() for l in lines[1:50]]

KEYWORD_TAGS = [
    (re.compile(r"pruning|上下文|裁剪", re.I), ["ContextPruning"]),
    (re.compile(r"QMD|检索|向量", re.I), ["QMD", "Memory"]),
    (re.compile(r"cron|定时任务", re.I), ["Cron"]),
    (re.compile(r"模型|路由|分层|routing|model", re.I), ["ModelRouting"]),
]

PATH_TAGS = [
    ("/01-Articles/OpenClaw/", ["OpenClaw", "AIAgent"]),
    ("/01-Articles/Knowledge/", ["Knowledge", "Archive"]),
    ("/01-Articles/Learning/", ["Learning", "Notes"]),
    ("/03-Projects/", ["Project", "Engineering"]),
]

CATEGORY_BY_PATH = [
    ("/01-Articles/OpenClaw/", "OpenClaw"),
    ("/01-Articles/Knowledge/", "研报/归档"),
    ("/01-Articles/Learning/", "学习笔记"),
    ("/03-Projects/", "项目文档"),
]


def compute_tags(path: Path, text: str) -> list[str]:
    tags = ["KnowledgeBase"]
    p = "/" + "/".join(path.parts)
    for needle, ts in PATH_TAGS:
        if needle in p:
            tags += ts
    for rx, ts in KEYWORD_TAGS:
        if rx.search(text):
            tags += ts
    # uniq preserve order
    out = []
    for t in tags:
        if t not in out:
            out.append(t)
    return out


def compute_category(path: Path) -> str:
    p = "/" + "/".join(path.parts)
    for needle, cat in CATEGORY_BY_PATH:
        if needle in p:
            return cat
    return "工程实践"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root_dir")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    root = Path(args.root_dir)
    today = date.today().isoformat()

    files = [p for p in root.rglob('*.md') if p.is_file()]
    changed = 0
    for p in files:
        text = p.read_text(encoding='utf-8', errors='ignore')
        if has_frontmatter(text):
            continue
        title = p.stem
        tags = compute_tags(p, text)
        category = compute_category(p)
        fm = (
            "---\n"
            f"title: {title}\n"
            "aliases: []\n"
            f"category: {category}\n"
            f"created: {today}\n"
            f"updated: {today}\n"
            f"tags: [{', '.join(tags)}]\n"
            "---\n\n"
        )
        new_text = fm + text
        changed += 1
        if args.dry_run:
            print("[dry]", p)
        else:
            p.write_text(new_text, encoding='utf-8')
            print("[ok]", p)

    print("changed", changed)

if __name__ == '__main__':
    main()
